name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.164.246.199 << 'EOF'
            set -e
            cd /davinci/DavinciClient
            git switch main
            git pull origin main

            docker compose stop nextjs || true
            docker compose rm -f nextjs || true

            echo "빌드 시작"
            docker compose build nextjs &

            while kill -0 $! 2> /dev/null; do
              echo "🛠 빌드 중... $(date)"
              sleep 10
            done

            docker compose up -d --force-recreate nextjs

            echo "배포 완료"
            sleep 5
          EOF

