name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.164.246.199 << 'EOF'
            set -e
            cd /davinci/DavinciClient
            git switch main
            git pull origin main

            docker compose down --remove-orphans || true
            docker rm -f davinci-nextjs || true
            docker ps -q --filter "publish=3000" | xargs -r docker rm -f || true

            echo "Docker cache cleanup"
            docker system prune -af || true
            docker builder prune -af || true

            echo "Build start"
            docker compose build nextjs

            docker compose up -d --force-recreate nextjs

            echo "Deploy complete"
            sleep 5
          EOF
